### PR TITLE
Fix sort order for SQLite tables

### LINKED ISSUE #333: Fix sort order for SQLite tables
See https://github.com/observablehq/feedback/issues/512

### PR DESCRIPTION
**Pull request by libbey-observable**
Resolves #333

- Adds `ORDER BY schema, name` to `describeTables`

Before|After
-|-
Screen Shot 2022-11-30 at 12 56 34 PM|Screen Shot 2022-11-30 at 12 56 56 PM

### CODE REVIEW

File: src/sqlite.js [hunk 1]
```diff
@@ -29,7 +29,7 @@ export class SQLiteDatabaseClient {
     ]);
   }
   async describeTables({schema} = {}) {
-    return this.query(`SELECT NULLIF(schema, 'main') AS schema, name FROM pragma_table_list() WHERE type = 'table'${schema == null ? "" : ` AND schema = ?`} AND name NOT LIKE 'sqlite_%'`, schema == null ? [] : [schema]);
+    return this.query(`SELECT NULLIF(schema, 'main') AS schema, name FROM pragma_table_list() WHERE type = 'table'${schema == null ? "" : ` AND schema = ?`} AND name NOT LIKE 'sqlite_%' ORDER BY name`, schema == null ? [] : [schema]);
```
Comment (CobusT) [inline src/sqlite.js:32]:
```suggestion
    return this.query(`SELECT NULLIF(schema, 'main') AS schema, name FROM pragma_table_list() WHERE type = 'table'${schema == null ? "" : ` AND schema = ?`} AND name NOT LIKE 'sqlite_%' ORDER BY schema, name`, schema == null ? [] : [schema]);
```

Comment (CobusT) [reply src/sqlite.js:32]: Should we order by schema first?

Comment (libbey-observable) [reply src/sqlite.js]: Thank you, @CobusT!

**Review by CobusT — APPROVED** [review]
LGTM. Not sure if you want to wait for Mike's approval, but looks good to me.

**Comment by libbey-observable** [comment]
> LGTM. Not sure if you want to wait for Mike's approval, but looks good to me.

I'll go with his thumbs up to ordering by schema first, and call this good.
